### ISSUE TITLE
Set temperature is only maintained for a certain time and then breaks off

### ISSUE THREAD

**Issue by userbasti** [avollkopf/cbpi4-BM_PID_SmartBoilWithPump#11]
In auto mode, I can set a temperature, this is then also started and held for a certain time - so far so good. But then something happens and it breaks off. To be more precise, the buttons of the heating and pump are no longer highlighted in green, but the button of the auto mode is still highlighted in green, the LEDs (on the dashboard) for the pump and heating are off, the last percentage value of the heating stops and the control no longer works (pump and heating are off).
It seems to be related to the pump pauses. If I enter in the fields Rest_Interval and Rest_Time as value 0 then it works. As I read in the description of the plugin, the function of the pump rest should actually only be active in the mashing process. Maybe it helps to narrow down the issue a bit.

**Comment by Blom1974** [comment]
> In auto mode, I can set a temperature, this is then also started and held for a certain time - so far so good. But then something happens and it breaks off. To be more precise, the buttons of the heating and pump are no longer highlighted in green, but the button of the auto mode is still highlighted in green, the LEDs (on the dashboard) for the pump and heating are off, the last percentage value of the heating stops and the control no longer works (pump and heating are off). It seems to be related to the pump pauses. If I enter in the fields Rest_Interval and Rest_Time as value 0 then it works. As I read in the description of the plugin, the function of the pump rest should actually only be active in the mashing process. Maybe it helps to narrow down the issue a bit.

Got the same issue. Seems related to pump pauses.

**Comment by avollkopf** [comment]
Does the issue also appear when you are using a step based recipe? I only use step based recipes to run a mash and this is now working for about 3 years w/o issues.

**Comment by avollkopf** [comment]
Looked a bit more into the code, and now I remember, that the plugin is really oriented on step based mashing. In particular, pump pause is done only, when a step is running and not during temperature ramp. Hence, Pump pause will not work if logic is not used for step based temp control. 

The plugin is intended for usage with the Speidel Braumeister, where pump rests make sense - but only during mash steps and not during temp ramp as this had the potential of temp overshooting shortly before target temp was reached w/ deactivated pump.

This was introduced 2 years ago: https://github.com/PiBrewing/cbpi4-BM_PID_SmartBoilWithPump/commit/43331b5fe6e3a04a77e69834598a5069c5e5bd1c

**Comment by avollkopf** [comment]
Should be fixed with this change: https://github.com/PiBrewing/cbpi4-BM_PID_SmartBoilWithPump/commit/3b7395234ed95a97ee10350c171059e689442410

Please report back and I can push this to the main repo and update also the pypi release.

**Comment by avollkopf** [comment]
fixed with #12
