### ISSUE TITLE
Setting pump rest period to 0 crashes cbpi

### ISSUE THREAD

**Issue by Wobbly74** [avollkopf/cbpi4-BM_PID_SmartBoilWithPump#6]
I tried setting this to 0 to turn off pump rests, as the default seems to be to rest after 10 minutes. Instead it seemed to cause cbpi to loop indefinitely, sending some fairly weird control signals to the pump (which just groaned a bit) and shooting cpu usage through the roof.

**Comment by avollkopf** [comment]
@Wobbly74 Please check the development branch. Update should fix the issue.

**Comment by Wobbly74** [comment]
Checked on 4.0.1a7 and it still seems to be broken - screen capture of behaviour: https://www.youtube.com/watch?v=-h3mpXy8ra0

**Comment by avollkopf** [comment]
@Wobbly74 This is not related to the cbpi server but to the plugin.

You need to install the development version of the plugin:
https://github.com/avollkopf/cbpi4-BM_PID_SmartBoilWithPump/tree/development

**Comment by Wobbly74** [comment]
D'oh. Yes, obvs of course. Ok, I've installed the dev branch of the plugin and that does seem to have corrected it now.

**Comment by avollkopf** [comment]
Thanks for the feedback. I will merge that into the main branch and close the issue.
